-- Oracle Free (23c) initialisation for kafka-wiremock examples.
-- Executed automatically by gvenzl/oracle-free as APP_USER (myuser) after first startup.
-- The APP_USER and database are created by the container entrypoint before this script runs.

-- ──────────────────────────────────────────────────────────────────────────────
-- order_audit table  (used by db-audit-rule.yaml)
-- Written to as a side-effect when an ORDER_CREATED event is processed by a rule.
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE order_audit (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   VARCHAR2(100) NOT NULL,
    event_type VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- ──────────────────────────────────────────────────────────────────────────────
-- products / orders tables  (mirror of MySQL schema — optional Oracle variant)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE products (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    price      NUMBER(10,2)  NOT NULL,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE orders (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER        NOT NULL,
    status     VARCHAR2(50)  DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_orders_product_id ON orders(product_id);

COMMIT;

